version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-major-minor:
        update-types: ["major", "minor"]
      go-patch:
        update-types: ["patch"]
